- name: Copy node exporter
  copy:
    src: roles/setup_node_exporter/files/node_exporter-0.17.0.linux-amd64.tar.gz
    dest: /tmp/node_exporter-0.17.0.linux-amd64.tar.gz

- name: Unarchive node exporter
  unarchive:
    src: /tmp/node_exporter-0.17.0.linux-amd64.tar.gz
    dest: /tmp
    remote_src: yes

- name: Create node_exporter user
  shell: "sudo useradd -rs /bin/false node_exporter"

- name: Copy node exporter
  copy:
    src: /tmp/node_exporter-0.17.0.linux-amd64/node_exporter
    dest: /usr/local/bin/node_exporter
    owner: node_exporter
    group: node_exporter
    mode: "u+rwx,g+rwx,o+rwx"
    remote_src: yes

# - name: Clean /opt path
#   file:
#     state: absent
#     path: "{{ item }}"
#     remote_src: yes
#   with_items:
#    - {'/tmp/node_exporter-0.17.0.linux-amd64/'}
#    - {'/tmp/node_exporter-0.17.0.linux-amd64.tar.gz'}

- name: Copy node exporter service to /etc/systemd/system
  copy:
    src: roles/setup_node_exporter/files/node_exporter.service
    dest: /etc/systemd/system/node_exporter.service

- name: Reload daemon
  systemd:
    daemon_reload: yes

- name: Start node_exporter
  systemd:
    state: started
    name: node_exporter

- name: Enable node_exporter
  systemd:
    name: node_exporter
    enabled: yes
    masked: no