- name: Prompt
  pause:
    prompt: |-
      Make sure you know what you are doing.
      Below instance will be renamed!
      (Hit ENTER to continue)

- name: Rename instance
  shell: |
    openstack --os-cloud {{ cloud }} server set --name {{ new_name }} {{ target }}