- name: Update apt packages
  become: true
  apt:
    update_cache: yes

- name: Install java
  retries: 2
  delay: 3
  register: result
  until: result is succeeded
  ignore_errors: yes
  apt:
    name: "openjdk-8-jdk"
    state: present
    update_cache: yes

- name: Import the GPG keys of the Jenkins repository
  shell: "wget -q -O - https://pkg.jenkins.io/debian/jenkins.io.key | sudo apt-key add -"

- name: Add the Jenkins repository to the system
  shell: "sh -c 'echo deb http://pkg.jenkins.io/debian-stable binary/ > /etc/apt/sources.list.d/jenkins.list'"

- name: Update apt packages
  become: true
  apt:
    update_cache: yes
    cache_valid_time: 86400 #One day

- name: Install jenkins
  retries: 2
  delay: 3
  register: result
  until: result is succeeded
  ignore_errors: yes
  apt:
    name: "jenkins"
    state: present
    update_cache: yes

